version: '2'

services:
  db:
    image: shevchenkoav/mongodb:3.2.6
    networks:
      - back

  blog_backend:
    image: shevchenkoav/blog_backend
    environment:
      - MONGO_HOST=db
    networks:
      - back
      - front

  blog_ui:
    image: shevchenkoav/blog_ui
    env_file:
      - blog-backend-vars.env
    ports:
      - "80:9292"
    networks:
      - front
networks:
  front:
    driver: bridge
  back:
    driver: bridge
